### ISSUE TITLE
第 2 题：flex 布局：flex: 1 1 auto; 是什么意思？flex-shrink 怎么计算

### ISSUE THREAD

**Issue by HbuJiaTian** [HbuJiaTian/daily-interview-question#4]
1. flex: 1 1 auto 代表着：元素会根据自身的宽度与高度来确定尺寸，但是会伸长并吸收 flex 容器中额外的自由空间，也会缩短自身来适应 flex 容器。
2. flex-shink 属性是flex属性值的第二个参数，主要是在外层div宽度不够的情况下，子div收缩一定的空间来抵消不够的那部分宽度。
举例，现在三个子div的宽度和是600px, 但是给外层div的宽度设置成500px, 那么不够显示的600-500 px应该怎么让子div们收缩掉这100px。这个时候flex-shrink就派上用场了，那具体怎么计算呢？
有人说这个属性跟flex-grow类似，计算方式也差不多吧(其实是不太一样的)。包括MDN, W3CShcool也没给出具体公式。下面是计算方法：
html部分：
``` html 
<div class="outer">
    <div class='div1'>1</div>
    <div class='div2'>2</div>
    <div class="div3">3</div>
</div>
```
css部分：
``` css
.outer {
  width: 500px;
  display: flex;
}
.outer div {
  height: 80px;
}

.div1 {
  flex: 1 1 100px;
  background: red;
}
.div2 {
  flex: 1 2 200px;
  background: yellow;
}
.div3 {
  flex: 1 3 300px;
  background: green;
}
```
先计算总权重TW = 100px * 1(flex-shrink) + 200px *2(flex-shrink) + 300px *3(flex-shrink) = 1800px 也就是每个div的宽度乘以flex-shrink系数的总和。
每个div收缩的空间为：div的宽度 * flex-shrink系数/ 总权重TW * 需要收缩的总宽度（在我们的例子中是600px - 500px = 100px）
所以各子div最后的宽度计算公式如下：
``` 
div1最后的宽度 = 100px - 100*1/1400 * 100px = 92.86px
div2最后的宽度 = 200px - 200*2/1400 * 100px = 171.42px
div3最后的宽度 = 300px - 300*3/1400 * 100px = 235.72px
```
大致效果如下：
![image](https://user-images.githubusercontent.com/10797390/65737924-a5de9700-e112-11e9-803d-327445ce4dd8.png)
